samples: "samples.tsv"

reference:
  genome: "reference/GRCh38.d1.vd1.fa"
  transcripts: "reference/gencode.v36.transcripts.fa"
  gtf: "reference/gencode.v36.annotation.gtf"
  tx2gene: "reference/tx2gene.tsv"

build_index: true
salmon_index: "resources/salmon_GRCh38.d1.vd1_GENCODEv36"

threads:
  index: 12
  salmon: 8
  fastqc: 2
  bam_to_fastq: 4
  sra_to_fastq: 6

salmon:
  libtype: "A"
  validateMappings: true
  seqBias: true
  gcBias: true
  # Add extra Salmon quant arguments here, e.g. "--numBootstraps 30"
  extra: ""
