samples: "metadata.tsv"

reference:
  genome: "reference/GRCh38.d1.vd1.fa"
  transcripts: "reference/gencode.v36.transcripts.fa"
  gtf: "reference/gencode.v36.annotation.gtf"
  tx2gene: "reference/tx2gene.tsv"

build_index: true
salmon_index: "resources/salmon_GRCh38.d1.vd1_GENCODEv36"

threads:
  index: 12
  salmon: 8
  fastqc: 2
  bam_to_fastq: 4
  sra_to_fastq: 6

salmon:
  libtype: "A"
  validateMappings: true
  seqBias: true
  gcBias: true
  # Add extra Salmon quant arguments here, e.g. "--numBootstraps 30"
  extra: ""




##########################################
# DESeq2
##########################################
#OrgDb: org.Mm.eg.db
OrgDb: org.Hs.eg.db



#Gene column in Gene_Level_Raw_Counts.txt
gene_id_type: ENSEMBL

#enrichr_databases:
#  - KEGG_2021_Mouse
#  - GO_Biological_Process_2023
# - GO_Cellular_Component_2023
# - GO_Molecular_Function_2023

enrichr_databases:
  - KEGG_2021_Human
  - WikiPathway_2023_Human
  - Reactome_2022
  - GO_Biological_Process_2023
  - GO_Cellular_Component_2023
  - GO_Molecular_Function_2023

# Treatment column in metadata.txt
comparisons:

  # EZH2 enzymatic inhibition vs DMSO
  - group1: "EZH2 enzymatic inhibitor EPZ-6438"
    group2: "DMSO"

  # EZH2 PROTAC degradation vs DMSO
  - group1: "EZH2 PROTAC degrader PROTAC-6272"
    group2: "DMSO"

  # VHL-inactive PROTAC control vs DMSO
  - group1: "VHL-inactive control compound 6286"
    group2: "DMSO"

  # Active EZH2 PROTAC vs VHL-inactive control
  - group1: "EZH2 PROTAC degrader PROTAC-6272"
    group2: "VHL-inactive control compound 6286"

  # EZH2 degradation vs EZH2 enzymatic inhibition
  - group1: "EZH2 PROTAC degrader PROTAC-6272"
    group2: "EZH2 enzymatic inhibitor EPZ-6438"

  # EZH2 enzymatic inhibitor vs VHL-inactive control
  - group1: "EZH2 enzymatic inhibitor EPZ-6438"
    group2: "VHL-inactive control compound 6286"
